[versions]
androidGradlePlugin = "8.12.3"
arrowCore = "2.1.2"
datastorePreferences = "1.1.7"
desugar_jdk_libs = "2.1.5"
exifinterface = "1.4.1"
hilt = "2.57.1"
javaStringSimilarity = "2.0.0"
kotlin = "2.2.10"
kotlinxSerialization = "1.9.0"
ksp = "2.2.10-2.0.2"
kotlinx = "1.10.2"
navigation = "2.9.3"
room = "2.7.2"
lifecycle = "2.9.3"
media3 = "1.8.0"
transformations = "3.0.7"
viewpump = "2.1.1"
work = "2.10.3"
coil = "3.3.0"
retrofit = "3.0.0"
jetbrainsKotlinJvm = "2.2.10"
commonmark = "0.13.0" # DO NOT BUMP THIS PAST 0.13.0

[libraries]
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrowCore" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version = "1.3.0" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinxSerialization" }
slidingpanelayout = { module = "androidx.slidingpanelayout:slidingpanelayout", version = "1.2.0" }
interpolator = { module = "androidx.interpolator:interpolator", version = "1.0.0" }

java-string-similarity = { module = "info.debatty:java-string-similarity", version.ref = "javaStringSimilarity" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx" }

navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version = "2.2.0" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle"}

media3-core = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3"}
media3-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "media3" }

okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version = "5.1.0" }
okhttp-okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-intercepter = { module = "com.squareup.okhttp3:logging-interceptor" }

retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit2-converter-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }

transformations = { module = "com.github.Commit451.coil-transformations:transformations", version.ref = "transformations" }
viewpump = { module = "io.github.inflationx:viewpump", version.ref = "viewpump" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil"}
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

ksoup = { module = "com.fleeksoft.ksoup:ksoup", version = "0.2.5" }
material = { module = "com.google.android.material:material", version = "1.14.0-alpha04" }
disklrucache = { module = "com.jakewharton:disklrucache", version = "2.0.2" }
gson = { module = "com.google.code.gson:gson", version = "2.13.1" }
process-phoenix = { module = "com.jakewharton:process-phoenix", version = "3.0.0" }

# AndroidX
core = { module = "androidx.core:core", version = "1.17.0" }
core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
window = { module = "androidx.window:window", version = "1.4.0" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
browser = { module = "androidx.browser:browser", version = "1.9.0" }
cardview = { module = "androidx.cardview:cardview", version = "1.0.0" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.4.0" }
preference-ktx = { module = "androidx.preference:preference-ktx", version = "1.2.1" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }
#swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.2.0-beta01" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version = "1.8.9" }
activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.10.1" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
transition-ktx = { module = "androidx.transition:transition-ktx", version = "1.6.0" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
documentfile = { module = "androidx.documentfile:documentfile", version = "1.1.0" }
annotation = { module = "androidx.annotation:annotation", version = "1.9.1"}
asynclayoutinflater = { module = "androidx.asynclayoutinflater:asynclayoutinflater", version = "1.1.0" }

hilt-common = { module = "androidx.hilt:hilt-common", version = "1.2.0"}
hilt-work = { module = "androidx.hilt:hilt-work", version = "1.2.0" }
#hilt-compiler = { module = "androidx.hilt:hilt-compiler", version = "1.2.0" }

commonmark = { module = "com.atlassian.commonmark:commonmark", version.ref = "commonmark"}
commonmark-strikethrough = { module = "com.atlassian.commonmark:commonmark-ext-gfm-strikethrough", version.ref = "commonmark"}
commonmark-table = { module = "com.atlassian.commonmark:commonmark-ext-gfm-tables", version.ref = "commonmark"}

tools-patreon = { module = "com.patreon:patreon", version = "0.4.2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android-extensions = { id = "org.jetbrains.kotlin.android.extensions", version.ref = "kotlin" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "13.0.0" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
versions = { id = "com.github.ben-manes.versions", version = "0.52.0" }
sentry = { id = "io.sentry.android.gradle", version = "5.9.0"}